URL = "https://images.unsplash.com/photo-1740021778104-6d4abe5808cc?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

KWARGS = "flags=cv.IMREAD_COLOR"

all: 
	python3 load_image_from_url.py --url $(URL) --kwargs $(KWARGS)