REGISTRATION_NUMBER = 22111532
WIDTH = 500
HEIGHT = 500
MEAN = 128
STD = 50
OUTPUT = "./generated_images/out.jpg"

all: 
	python3 task-01-generate-an-image.py \
	--registration_number $(REGISTRATION_NUMBER) \
	--width $(WIDTH) \
	--height $(HEIGHT) \
	--mean $(MEAN) \
	--std $(STD) \
	--output $(OUTPUT)
